server-messages:
  # The message that will be sent to the player when they join the server
  join: "&aWelcome to the server, %player%!"

  # The message that will be sent to the player when they leave the server
  leave: "&cGoodbye, %player%!"

auto-broadcast:
  # The Duration between each broadcast in seconds
  interval: 300

  # The messages that will be broadcasted
  broadcast-messages:
    "1":
      - "&8&m---------------------&r &a&lBUYCRAFT &8&m---------------------"
      - "&eKunne du godt tænke dig at &astøtte &eos? Benyt &a/buy &e for at kunne"
      - "&ekøbe &6coins&e! Disse &6coins &ekan du bruge til at købe &6ranks &eog &6kits&e!"
      - "&8&m---------------------&r &a&lBUYCRAFT &8&m---------------------"
    "2":
      - "&8&m---------------------&r &9&lDISCORD &8&m---------------------"
      - "&eVil du gerne være opdateret på alt der sker på serveren?"
      - "&eSå er du velkommen til at join vores &9Discord &eserver!"
      - "&eDu kan joine ved at benytte &9/discord&e!"
      - "&8&m---------------------&r &9&lDISCORD &8&m---------------------"
    "3":
      - "&8&m---------------------&r &6&lKIT RATE &8&m---------------------"
      - "&eVil du gerne vil støtte os? Så kan du gøre det ved at rate os!"
      - '&eDu kan rate os ved at benytte &6"/rate g s navn +"&ei limbo.'
      - '&eSom tak for din støtte, vil du modtage adgang til &6"/kit rate"&e!'
      - "&8&m---------------------&r &6&lKIT RATE &8&m---------------------"

  # Toggles the auto-broadcast for certain messages
  broadcast-toggles:
    guard-buy: false # Toggles the broadcast for the guard buy message
    guard-applications: false # Toggles the broadcast for the guard applications message
    staff-applications: false # Toggles the broadcast for the staff applications message

  # The messages that will be broadcasted if the toggle is enabled
  broadcast-toggles-messages:
    "guard-buy":
      - "&8&m---------------------&r &c&lVAGT KØB &8&m---------------------"
      - "&eVil du gerne være en del af vores &cVagt &eteam, med et hyggeligt fællesskab?"
      - "&eSå kan du &6måske &ekøbe en &cP-Vagt &erank ved at læse mere i &6/buy&c!"
      - "&8&m---------------------&r &c&lVAGT KØB &8&m---------------------"
    "guard-applications":
      - "&8&m------------------&r &c&lVAGT ANSØGNING &8&m------------------"
      - "&eVil du gerne være en del af vores &cVagt &eteam, med et hyggeligt fællesskab?"
      - "&eSå kan du &6ansøge &etil at blive en &cP-Vagt&e! &aLæs mere på vores discord&e!"
      - "&8&m------------------&r &c&lVAGT ANSØGNING &8&m------------------"
    "staff-applications":
      - "&8&m------------------&r &b&lSTAFF ANSØGNING &8&m------------------"
      - "&eVil du gerne være en del af vores &cStaff &eteam, og være med til at gavne serveren?"
      - "&eSå kan du &6ansøge &etil at blive en &9Hjælper&e! &aLæs mere på vores discord&e!"
      - "&8&m------------------&r &b&lSTAFF ANSØGNING &8&m------------------"

anti-craft:
  # The message that will be sent to the player when they try to craft a blacklisted item
  message: "&cYou are not allowed to craft this item!"

  # The items that are blacklisted as IDs
  blacklisted-items:
    - 166
    - 120
    #- 0

anti-place:
  # The message that will be sent to the player when they try to place a blacklisted block
  message: "&cYou are not allowed to place this block!"

  # The blocks that are blacklisted as IDs
  blacklisted-blocks:
    - 120
    #- 0

blocked-commands:
  # The message that will be sent to the player when they try to execute a blacklisted command
  message: "&cYou are not allowed to execute this command!"

  # The UUIDs of the players that are allowed to execute blacklisted commands
  allowed-players:
    #- '00000000-0000-0000-0000-000000000000' # This is an example UUID
    - "7d82e51e-253e-4133-9454-002ba73e3174" # PandaPeter

  # The commands that are blacklisted
  blacklisted-commands:
    - "blockedcommands" # does not do anything anyway, but leave it as an example command
    - "minecraft:op"
    - "minecraft:deop"
    - "minecraft:me"
    - "minecraft:tell"
    - "minecraft:pl"
    - "minecraft:plugins"
    - "op"
    - "deop"
    - "me"
    - "tell"
    - "pl"
    - "plugins"
    - "gamerule"
    - "nuke"
    - "kickall"
    - "say"
    - "spigot:pl"
    - "spigot:plugins"
    - "eme"
    - "ac"
    - "essentials:ac"
    - "helpop"
    - "ehelop"
    - "essentials:helpop"
    - "essentials:ehelpop"
    - "bukkit:pl"
    - "bukkit:plugins"
    - "ept"
    - "epowertool"
    - "essentials:pt"
    - "essentials:powertool"
    - "pt"
    - "powertool"
    - "stop"
    - "icanhasbukkit"
    - "lockdown"
    - "litebans:lockdown"