name: PinkCore
version: '${project.version}'
main: org.pinkprison.pinkcore.PinkCore
authors: [ PandaPeter, MartinErSej, Champen_V1ldtand ]
description: Simple core functionality for plugins used by pink
